### ISSUE TITLE
Retirement of Office 365 connectors within Microsoft Teams

### ISSUE THREAD

**Issue by ljanissen** [wwwjk366/teamr#5]
We send Teams notification cards from R-scripts and this morning (8-July-2024) all notifications had the following message appended:

"Action Required:
O365 connectors within Teams will be deprecated and notifications from this service will stop.
[Learn more](https://aka.ms/O365ConnectorDeprecation)
about the timing and how the Workflows app provides a more flexible and secure experience. If you want to continue receiving these types of messages, you can use a workflow to post messages from a webhook request."

Here is an example of how we use teamr to post notifications:

cc <- connector_card$new(hookurl = "Our webhook")
cc$title(paste0("Daily Blotter - ", trade.date))
cc$text("Please find the daily blotter:")
cc$color("#008000")
cc$send()

**Comment by ljanissen** [comment]
Issue resolved by recreating webhooks via the Teams Workflows app

**Comment by NateDawkins** [comment]
Hi @ljanissen, would you have an example to propose to replace the old way of working with the new webhooks via the Teams Workflows app?
I tried to make the change on my side but I have errors and I'm not sure that I understand everything...
Thanks in advance

**Comment by ljanissen** [comment]
You have to set up a workflow in Power Automate.  

![image](https://github.com/wwwjk366/teamr/assets/34487162/0bd40481-44e1-41f1-88d5-98602f7b1cdf)

The default action for this template is "adaptive card" but we haven't been able to make that work yet, so we use the Parse JSON and Post message in a chat or channel actions:

![Screenshot 2024-07-10 084658](https://github.com/wwwjk366/teamr/assets/34487162/3645075e-d438-4a6c-bea2-8fbd7aa97553)

The webhook is generated in the first connector, which you can call from the R script:
![image](https://github.com/wwwjk366/teamr/assets/34487162/ab452743-df7f-4e8e-9b58-e5bc3855d95b)

![image](https://github.com/wwwjk366/teamr/assets/34487162/0efb47e9-7b68-4031-9eb5-5c5606e3ad78)

`{
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "text": {
            "type": "string"
        },
        "color": {
            "type": "string"
        }
    }
}`

Here is the final piece:
![image](https://github.com/wwwjk366/teamr/assets/34487162/9b9b154a-6620-41fc-ade6-821eaac2c3ba)

**Comment by NateDawkins** [comment]
Thank you very much for your reply, it helped me a lot!
Have a nice day!
